name: Docker buildx

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check if rust-lang/docker-rust updated in last 1 day
        id: check
        run: |
          OUTPUT=$(python3 check_update.py) &&
          echo "::set-output name=OUTPUT::$OUTPUT"
      -
        if: steps.check.outputs.OUTPUT == 1
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        if: steps.check.outputs.OUTPUT == 1
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        if: steps.check.outputs.OUTPUT == 1
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        if: steps.check.outputs.OUTPUT == 1
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: bittwilight/dev-environments-rust:latest
